// <auto-generated />
using ExpensesTracker.Backend.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpensesTracker.Backend.Migrations
{
    [DbContext(typeof(ExpensesContext))]
    [Migration("20250907212952_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "This category is for bills.",
                            Name = "Bills"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "This category is for housing costs.",
                            Name = "Housing Costs"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "This category is for shopping costs.",
                            Name = "Shopping"
                        });
                });

            modelBuilder.Entity("Shared.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("DueDate")
                        .HasColumnType("int");

                    b.Property<int>("FrequencyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExpenseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FrequencyId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            ExpenseId = 1,
                            Amount = 20.99m,
                            CategoryId = 1,
                            DueDate = 12,
                            FrequencyId = 1,
                            IsPaid = false,
                            Name = "Phone Bill"
                        },
                        new
                        {
                            ExpenseId = 2,
                            Amount = 20.99m,
                            CategoryId = 1,
                            DueDate = 10,
                            FrequencyId = 1,
                            IsPaid = false,
                            Name = "Water Bill"
                        },
                        new
                        {
                            ExpenseId = 3,
                            Amount = 200.99m,
                            CategoryId = 2,
                            DueDate = 8,
                            FrequencyId = 1,
                            IsPaid = false,
                            Name = "Rent"
                        },
                        new
                        {
                            ExpenseId = 4,
                            Amount = 20.99m,
                            CategoryId = 3,
                            DueDate = 11,
                            FrequencyId = 2,
                            IsPaid = false,
                            Name = "Asda Grocery Shopping"
                        });
                });

            modelBuilder.Entity("Shared.Models.Frequency", b =>
                {
                    b.Property<int>("FrequencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrequencyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FrequencyId");

                    b.ToTable("Frequencies");

                    b.HasData(
                        new
                        {
                            FrequencyId = 1,
                            Name = "Monthly"
                        },
                        new
                        {
                            FrequencyId = 2,
                            Name = "Once Only"
                        });
                });

            modelBuilder.Entity("Shared.Models.Income", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncomeId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IncomeId");

                    b.ToTable("Income");

                    b.HasData(
                        new
                        {
                            IncomeId = 1,
                            Amount = 1000m,
                            Name = "Salary"
                        });
                });

            modelBuilder.Entity("Shared.Models.Expense", b =>
                {
                    b.HasOne("Shared.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Frequency", "Frequency")
                        .WithMany()
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Frequency");
                });
#pragma warning restore 612, 618
        }
    }
}
